// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwIrP8BwKbYAeuo_c31501uUdZrKcyi5A',
    appId: '1:751689288448:web:461c9e395a7780fa3c41e5',
    messagingSenderId: '751689288448',
    projectId: 'amir-pos',
    authDomain: 'amir-pos.firebaseapp.com',
    storageBucket: 'amir-pos.appspot.com',
    measurementId: 'G-WKBBF67WLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEY_ch9m6i2m6tXU9ojW6j19HkMvBddE',
    appId: '1:751689288448:android:42329f9f1ba48d8c3c41e5',
    messagingSenderId: '751689288448',
    projectId: 'amir-pos',
    storageBucket: 'amir-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN7lw9nbbwhqp-iH593NS9QcvFLBqZ4D0',
    appId: '1:751689288448:ios:fa32b5c639cb79d63c41e5',
    messagingSenderId: '751689288448',
    projectId: 'amir-pos',
    storageBucket: 'amir-pos.appspot.com',
    iosBundleId: 'com.example.pointOfSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN7lw9nbbwhqp-iH593NS9QcvFLBqZ4D0',
    appId: '1:751689288448:ios:fa32b5c639cb79d63c41e5',
    messagingSenderId: '751689288448',
    projectId: 'amir-pos',
    storageBucket: 'amir-pos.appspot.com',
    iosBundleId: 'com.example.pointOfSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwIrP8BwKbYAeuo_c31501uUdZrKcyi5A',
    appId: '1:751689288448:web:614f2f1e4b6555fe3c41e5',
    messagingSenderId: '751689288448',
    projectId: 'amir-pos',
    authDomain: 'amir-pos.firebaseapp.com',
    storageBucket: 'amir-pos.appspot.com',
    measurementId: 'G-M0QV26D9GP',
  );
}
